/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// The accessory of the artifact
type Accessory struct {
	// The ID of the accessory
	Id int64 `json:"id,omitempty"`
	// The artifact id of the accessory
	ArtifactId int64 `json:"artifact_id,omitempty"`
	// The subject artifact id of the accessory
	SubjectArtifactId int64 `json:"subject_artifact_id,omitempty"`
	// The artifact size of the accessory
	Size int64 `json:"size,omitempty"`
	// The artifact digest of the accessory
	Digest string `json:"digest,omitempty"`
	// The artifact size of the accessory
	Type_ string `json:"type,omitempty"`
	// The icon of the accessory
	Icon string `json:"icon,omitempty"`
	// The creation time of the accessory
	CreationTime time.Time `json:"creation_time,omitempty"`
}
